name: inception

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - jjhangNet

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - jjhangNet

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d
      - ${CERTS_}:/etc/nginx/certs
    networks:
      - jjhangNet

networks:
  jjhangNet:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOST_DATA}/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOST_DATA}/wordpress
      o: bind