name: Inception42

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./requirements/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - jjhangNet
      
volumes:
  mariadb-data:

networks:
  jjhangNet: