name: inception42

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wp
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - jjhangNet

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-content:/var/www/html/wp-content
    networks:
      - jjhangNet
    expose:
      - "9000"

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress-content:/var/www/html/wp-content
    networks:
      - jjhangNet

volumes:
  mariadb-data:
  wordpress-content:

networks:
  jjhangNet: