name: inception42

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    user: "1000:1000"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wp
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - /home/jjhang/data/mariadb:/var/lib/mysql
    networks:
      - jjhangNet

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    user: "1000:1000"
    expose:
      - "9000"
    volumes:
      - /home/jjhang/data/wordpress:/var/www/html
    networks:
      - jjhangNet

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    user: "1000:1000"
    ports:
      - "443:443"
    volumes:
      - /home/jjhang/data/wordpress:/var/www/html
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d
      - ./requirements/nginx/certs:/etc/nginx/certs
    networks:
      - jjhangNet

networks:
  jjhangNet: